xaque208/puppet-bsd

lib/puppet_x/bsd/hostname_if.rb
spec/defines/bsd_network_interface_spec.rb

Adding vether to the supported list means that the interface is
expected to have already been processed.  This is not quite so.  Until
we build a bsd::network::interface::vether define, we need not include
vether in the supported list, as implementing an interface with vether
does not require it.  The bsd::network::interface can be used directly.

The vehter remains unprocessed

---

README.md
lib/puppet/parser/functions/get_hostname_if_wifi.rb
lib/puppet_x/bsd/hostname_if.rb
lib/puppet_x/bsd/hostname_if/wifi.rb
manifests/network/interface/wifi.pp
spec/unit/bsd/hostname_if/wifi_spec.rb
tests/openbsd_wifi.pp

i.e. allow unencrypted wifi network configuration.
Update specs to reflect that change, add a few more wifi interfaces
I own and reorder them alphabetically. Add a little test.
Travis fails, due to :lint test in Rakefile,
removing that :lint test, tests are passing.
Don't know why it is failing, but puppet-lint also fails for me on
my local box with the same error on your master branch, without
me doing any changes :(

Allow wifi interfaces configuration without requiring a network_key,

---

lib/puppet_x/bsd/rc_conf.rb

This ensures that only in-scope variables are used as part of the
resecue.

Fix a failed rescue

---

lib/puppet/provider/bsd_interface/ifconfig.rb
lib/puppet_x/bsd/rc_conf.rb
spec/unit/bsd/rc_conf_spec.rb

Without this commit, 'dhcp' was not an allowed string in the values
array and would fail with a terrible error.  This adds a test for such a
case, and modifies the logic to work with interfaces configured by DHCP
on FreeBSD.

Add test for a DHCP interface on FreeBSD

---

lib/puppet_x/bsd/hostname_if.rb
lib/puppet_x/bsd/hostname_if/inet.rb
spec/unit/bsd/hostname_if/inet_spec.rb
spec/unit/bsd/hostname_if_spec.rb

I finally got around to look into that, but it's not really for merge yet, just to show off and discuss ;)
This allows to set 'inet6 autoconf' on one line, and get it propagated into hostname.if
however, I tried to add the versioncmp in there, to in case rtsol is given for 5.7 or higher, automatically replace with inet6 autoconf, and vice versa, if inet6 autoconf is given, for machines
with kernelversion < 5.7, return rtsol. However, on my 5.7... box, when I give rtsol, I end up with rtsol in hostname.if file, irregardless how I switch the comparisons... :(
I guess its just a stupid thing I get wrong, but don't see it right now. Do you have a cluebat maybe?
Cheers,
Sebastian

Add inet6 autoconf, additionally to rtsol

---

lib/puppet_x/bsd/rc_conf/vlan.rb
spec/unit/bsd/rc_conf/vlan_spec.rb

Without this change, the code throws an "unknown method 'length'"
message due to the code treating the id as a string.
This work allows the id to be passed as an integer.

Fix error when vlan id is passed as an integer

---

lib/puppet_x/bsd/hostname_if/carp.rb
lib/puppet_x/bsd/hostname_if/trunk.rb
lib/puppet_x/bsd/hostname_if/vlan.rb
lib/puppet_x/bsd/hostname_if/wifi.rb
lib/puppet_x/bsd/rc_conf/vlan.rb
lib/puppet_x/bsd/util.rb
spec/unit/bsd/rc_conf/vlan_spec.rb

This just cleans up the config validation code so we centralize its use
in a single place.  Without this change, the code is a bit noisier than
it otherwise would be.

Standardize validation for hostname_if

---

lib/puppet/provider/bsd_interface/freebsd.rb
lib/puppet/provider/bsd_interface/ifconfig.rb
lib/puppet/provider/bsd_interface/openbsd.rb
lib/puppet/type/bsd_interface.rb
manifests/network/interface.pp

This enables refresh for the bsd_interface in a platform specific way.
Resources may now use the notify/subscribe meta-params.  If a resource is
notified, the provider will execute the platform specific method for
restarting an interface.

Implement platform providers for bsd_interface

---

.travis.yml

Both platforms that this module supports ship with 2.x versions of Ruby
and I'd like not to support 1.9 anymore.  Here we drop testing support.

Drop support for ruby 1.9

---

lib/puppet_x/bsd/hostname_if/trunk.rb
manifests/network/interface/trunk.pp
spec/defines/bsd_network_interface_trunk_spec.rb

Without this change, addresses do not get configured correctly on trunk
interfaces.

Support addresses on trunk interfaces

---

README.md

I was briefly confused by the difference between the xaque208 namespace on github and the zleslie one on puppet forge, so this helps document where the module can be found on puppet forge.

Add "Installation" section to readme

---

README.md
manifests/network/interface/bridge.pp
manifests/network/interface/carp.pp
manifests/network/interface/trunk.pp
manifests/network/interface/vlan.pp
manifests/network/interface/wifi.pp
spec/defines/bsd_network_interface_bridge_spec.rb
spec/defines/bsd_network_interface_carp_spec.rb
spec/defines/bsd_network_interface_vlan_spec.rb
spec/defines/bsd_network_interface_wifi_spec.rb

The values parameter, an array of strings, is intended to allow the user to set alias IP addresses, as well as shell commands, i.e. setting routes via !commands.
The values array, if given, is concatenated to the returned string of get_hostname_if_<INTERFACE_TYPE> functions, and then handed over to the values parameter of 'bsd::network::interface'
I only need it soon for carp interfaces, but thought all classes in that subdirectory should follow the same pattern, so I added it for all of them.
However, the vlan.pp was not following the pattern of the others, and now the FreeBSD test for vlan interfaces fails. I don't have a FreeBSD system around to test that. Do you have a possibility to verify that it creates a valid working FreeBSD config?
On OpenBSD, the config it created for VLAN …

fix issue #75: add values parameter to all network/interface/*.pp classes

---

README.md
lib/puppet/parser/functions/get_freebsd_rc_conf_shellconfig.rb
lib/puppet/parser/functions/get_openbsd_hostname_if_content.rb
lib/puppet_x/bsd/hostname_if.rb
lib/puppet_x/bsd/rc_conf.rb
manifests/network/interface.pp
spec/defines/bsd_network_interface_spec.rb
spec/unit/bsd/rc_conf_spec.rb

Process addresses in a separate function in hostname_if.rb, but keep the
old address parsing in process_items for backward compatibility.
Add addresses parameter to manifests::network::interface, and pass it
to get_openbsd_hostname_if_content function
Add a spec test using the addresses parameter in the bsd_network_interface_spec.rb
and update README.md
Add addresses parameter handling for FreeBSD too
Merge values into addresses in FreeBSD case in rc_conf.rb
Add deprecation warning to hostname_if.rb if IP address info is set
via values parameter, but no addresses parameter is given.
Bail out, when trying to set IP info via values parameter and an
addresses parameter is given too.
The big advantage is, that this way, IP addresses can be a bit more specifically validated, at some point in …

Separate address parser

---

README.md
lib/puppet/type/bsd_interface.rb
lib/puppet_x/bsd/hostname_if.rb
lib/puppet_x/bsd/rc_conf.rb
manifests/network/interface.pp
manifests/network/interface/bridge.pp
manifests/network/interface/carp.pp
manifests/network/interface/trunk.pp
manifests/network/interface/vlan.pp
spec/defines/bsd_network_interface_bridge_spec.rb
spec/defines/bsd_network_interface_carp_spec.rb
spec/defines/bsd_network_interface_spec.rb
spec/defines/bsd_network_interface_trunk_spec.rb
spec/defines/bsd_network_interface_vlan_spec.rb

Add a parents parameter to bsd::network::interface. This
can be a string or an array. The value of that parameter
is passed to Bsd_interface.rb when the interface is started.
Add a parents parameter to bsd_interface.rb, and autorequire
the parents. A bit of validation etc. of the interface name
done.
In bsd::network::interface, require the creation of hostname.if
for OpenBSD or the shell_config for FreeBSD to be done before
the Bsd_interface is created.
The subclasses in bsd::network::interface::* where parent interfaces
make sense to set, i.e. bridge, carp, trunk and vlan, deduct the
parent interface based on the interface or device parameter, and
hand that over to the parents parameter of bsd::network::interface.
Specs added for bsd::network::interface::* defined types, and
the parents …

Handle parent interfaces

---

lib/puppet_x/bsd/hostname_if/trunk.rb
lib/puppet_x/bsd/hostname_if/vlan.rb
spec/unit/bsd/hostname_if/trunk_spec.rb
spec/unit/bsd/hostname_if/vlan_spec.rb

Add a check in puppet_x/bsd/hostname_if/trunk.rb, to validate
the trunkprotos to only accept valid ones.
Add a check in puppet_x/bsd/hostname_if/vlan.rb to validate
valid vlan ids.
Add some spec tests to verify it's bailing out if invalid
values given.

Add some validation of trunkprotos and vlan IDs

---

lib/puppet_x/bsd/hostname_if/carp.rb
spec/defines/bsd_network_interface_carp_spec.rb
spec/defines/bsd_network_interface_vlan_spec.rb
spec/defines/bsd_network_interface_wifi_spec.rb
spec/unit/bsd/hostname_if/carp_spec.rb

Fixup carp with multiple addresses, and add specs to test for
that as well as adding specs for giving multiple values to
carp interfaces.
When there were multiple addresses given as an array, they were
only added onto a single line, breaking sh /etc/netstart carpXXX
Now correctly joining the data in lib/puppet_x/bsd/hostname_if/carp.rb
with a "\n" instead of the wrong ' '.
While there, I reordered the lines, like to have the same order
as done in the trunk interface.
Updating spec tests, to deal with that new order of lines, as well
as adding a test to check for IP addresses given as array as well
as values parameter given as array.
Second commit:
Add a multiple addresses spec test for vlan interfaces, and add
typos in wifi spec.

Fixup bsd::network::interface::carp with multiple addresses given

---

lib/puppet/provider/bsd_interface/ifconfig.rb
lib/puppet/type/bsd_interface.rb
lib/puppet_x/bsd/ifconfig.rb
spec/unit/bsd/ifconfig_spec.rb
spec/unit/puppet/provider/bsd_interface/ifconfig_spec.rb

The primary goal of this work is to reduce the number of calls to
ifconfig during execution.  On a low power system with lots of
interfaces, the calls to ifconfig represent a not-insignificant of the
total time for catalog application.

Implement flush

---

.fixtures.yml
.gitignore
lib/puppet/parser/functions/get_freebsd_rc_conf_shellvar.rb
lib/puppet_x/bsd/rc_conf.rb
manifests/network.pp
manifests/network/interface.pp
metadata.json
spec/defines/bsd_network_interface_spec.rb
spec/functions/get_freebsd_rc_conf_shellvar_spec.rb
spec/unit/bsd/rc_conf_spec.rb

This module now has three extra module dependencies, and drops
shell_config as a requirement.  The augeas providers are under active
development, and the providers are growing for a number of other types.
As such, to avoid needing two different modules that fundamentally do
the same thing, this change is my preference.
To update, simply have a look at the new dependencies and install the
needed modules.  If you are currently using shell_config elsewhere in
your environment, there will be no conflict, so you may go about your
day.  If you are not using shell_config elsewhere in your environment,
updating to this module would prove a reasonable time to remove stop
including it on your module list.

Update module dependencies

---

.fixtures.yml
README.md
manifests/network.pp
manifests/network/carp.pp
manifests/network/gre.pp
manifests/network/interface.pp
manifests/network/interface/pfsync.pp
manifests/network/interface/trunk.pp
manifests/network/interface/vlan.pp
metadata.json

The currently referenced sysctl module hasn't been committed to since 2015, and https://github.com/hercules-team/augeasproviders_sysctl has been active and is "Approved" on the Puppet Forge. This module does this through augeas and puppet-bsd already uses their code.
Additionally, I've revised a markdown error in the README that was breaking the lagg section. 
Every case statement has had a default specified per best practice.
https://docs.puppet.com/puppet/latest/reference/lang_conditional.html#aside-best-practices

Changing sysctl module

---

lib/puppet_x/bsd/rc_conf.rb
spec/unit/bsd/rc_conf_spec.rb

Without this change, raw_values are not respected on FreeBSD.  Here we take an
initial pass at correcting this.

Add support for raw_values on FreeBSD

---

.travis.yml
lib/puppet_x/bsd/hostname_if.rb
lib/puppet_x/bsd/hostname_if/inet.rb
spec/unit/bsd/hostname_if/inet_spec.rb
spec/unit/bsd/hostname_if_spec.rb

Here we drop the code that helped the transition to 5.7.  Users are now expected
to use 'inet6 autoconf' in place of 'rtsol'.  This change was part of the
migration to 5.7, which is long since past.  As such, we remove the code here
that worked to ensure compatibility.

Drop 5.7 rtsol support
